# coding: utf-8

"""
 Copyright 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License").
 You may not use this file except in compliance with the License.
 A copy of the License is located at

     http://www.apache.org/licenses/LICENSE-2.0

 or in the "license" file accompanying this file. This file is distributed
 on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 express or implied. See the License for the specific language governing
 permissions and limitations under the License.
"""

"""
    ProductAdvertisingAPI OffersV2 - DealDetails

    https://webservices.amazon.com/paapi5/documentation/offersV2.html
"""

import pprint
import re
import six


class OffersV2DealDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    
    Deal information for special offers.
    This field is only populated if there is a deal associated with the listing.
    """

    swagger_types = {
        'access_type': 'str',
        'badge': 'str',
        'start_time': 'str',
        'end_time': 'str',
        'early_access_duration_in_milliseconds': 'int',
        'percent_claimed': 'str'
    }

    attribute_map = {
        'access_type': 'AccessType',
        'badge': 'Badge',
        'start_time': 'StartTime',
        'end_time': 'EndTime',
        'early_access_duration_in_milliseconds': 'EarlyAccessDurationInMilliseconds',
        'percent_claimed': 'PercentClaimed'
    }

    def __init__(self, access_type=None, badge=None, start_time=None, end_time=None,  # noqa: E501
                 early_access_duration_in_milliseconds=None, percent_claimed=None):
        """OffersV2DealDetails - a model defined in Swagger"""  # noqa: E501

        self._access_type = None
        self._badge = None
        self._start_time = None
        self._end_time = None
        self._early_access_duration_in_milliseconds = None
        self._percent_claimed = None
        self.discriminator = None

        if access_type is not None:
            self.access_type = access_type
        if badge is not None:
            self.badge = badge
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if early_access_duration_in_milliseconds is not None:
            self.early_access_duration_in_milliseconds = early_access_duration_in_milliseconds
        if percent_claimed is not None:
            self.percent_claimed = percent_claimed

    @property
    def access_type(self):
        """Gets the access_type of this OffersV2DealDetails.

        Deal access type (ALL, PRIME_EARLY_ACCESS, PRIME_EXCLUSIVE)

        :return: The access_type of this OffersV2DealDetails.
        :rtype: str
        """
        return self._access_type

    @access_type.setter
    def access_type(self, access_type):
        """Sets the access_type of this OffersV2DealDetails.

        :param access_type: The access_type of this OffersV2DealDetails.
        :type: str
        """
        self._access_type = access_type

    @property
    def badge(self):
        """Gets the badge of this OffersV2DealDetails.

        Badge text describing the deal (e.g., "Limited time deal", "Ends in")

        :return: The badge of this OffersV2DealDetails.
        :rtype: str
        """
        return self._badge

    @badge.setter
    def badge(self, badge):
        """Sets the badge of this OffersV2DealDetails.

        :param badge: The badge of this OffersV2DealDetails.
        :type: str
        """
        self._badge = badge

    @property
    def start_time(self):
        """Gets the start_time of this OffersV2DealDetails.

        UTC deal start time (ISO8601 format)

        :return: The start_time of this OffersV2DealDetails.
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this OffersV2DealDetails.

        :param start_time: The start_time of this OffersV2DealDetails.
        :type: str
        """
        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this OffersV2DealDetails.

        UTC deal end time (ISO8601 format)

        :return: The end_time of this OffersV2DealDetails.
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this OffersV2DealDetails.

        :param end_time: The end_time of this OffersV2DealDetails.
        :type: str
        """
        self._end_time = end_time

    @property
    def early_access_duration_in_milliseconds(self):
        """Gets the early_access_duration_in_milliseconds of this OffersV2DealDetails.

        Duration in milliseconds for Prime Early Access deals

        :return: The early_access_duration_in_milliseconds of this OffersV2DealDetails.
        :rtype: int
        """
        return self._early_access_duration_in_milliseconds

    @early_access_duration_in_milliseconds.setter
    def early_access_duration_in_milliseconds(self, early_access_duration_in_milliseconds):
        """Sets the early_access_duration_in_milliseconds of this OffersV2DealDetails.

        :param early_access_duration_in_milliseconds: The early_access_duration_in_milliseconds.
        :type: int
        """
        self._early_access_duration_in_milliseconds = early_access_duration_in_milliseconds

    @property
    def percent_claimed(self):
        """Gets the percent_claimed of this OffersV2DealDetails.

        Percentage of deal capacity already consumed

        :return: The percent_claimed of this OffersV2DealDetails.
        :rtype: str
        """
        return self._percent_claimed

    @percent_claimed.setter
    def percent_claimed(self, percent_claimed):
        """Sets the percent_claimed of this OffersV2DealDetails.

        :param percent_claimed: The percent_claimed of this OffersV2DealDetails.
        :type: str
        """
        self._percent_claimed = percent_claimed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, attr_type in six.iteritems(self.swagger_types):
            value = getattr(self, attr, None)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true when self and other are equal"""
        if not isinstance(other, OffersV2DealDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true when self and other are not equal"""
        return not self == other
