# coding: utf-8

"""
 Copyright 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License").
 You may not use this file except in compliance with the License.
 A copy of the License is located at

     http://www.apache.org/licenses/LICENSE-2.0

 or in the "license" file accompanying this file. This file is distributed
 on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 express or implied. See the License for the specific language governing
 permissions and limitations under the License.
"""

"""
    ProductAdvertisingAPI OffersV2 - Listing

    https://webservices.amazon.com/paapi5/documentation/offersV2.html
"""

import pprint
import re
import six

from paapi5_python_sdk.offers_v2_availability import OffersV2Availability  # noqa: F401,E501
from paapi5_python_sdk.offers_v2_condition import OffersV2Condition  # noqa: F401,E501
from paapi5_python_sdk.offers_v2_deal_details import OffersV2DealDetails  # noqa: F401,E501
from paapi5_python_sdk.offers_v2_loyalty_points import OffersV2LoyaltyPoints  # noqa: F401,E501
from paapi5_python_sdk.offers_v2_merchant_info import OffersV2MerchantInfo  # noqa: F401,E501
from paapi5_python_sdk.offers_v2_price import OffersV2Price  # noqa: F401,E501


class OffersV2Listing(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    
    Offer listing for a product in OffersV2 format.
    This represents various offer listings associated with a product.
    """

    swagger_types = {
        'availability': 'OffersV2Availability',
        'condition': 'OffersV2Condition',
        'deal_details': 'OffersV2DealDetails',
        'is_buy_box_winner': 'bool',
        'loyalty_points': 'OffersV2LoyaltyPoints',
        'merchant_info': 'OffersV2MerchantInfo',
        'price': 'OffersV2Price',
        'type': 'str',
        'violates_map': 'bool'
    }

    attribute_map = {
        'availability': 'Availability',
        'condition': 'Condition',
        'deal_details': 'DealDetails',
        'is_buy_box_winner': 'IsBuyBoxWinner',
        'loyalty_points': 'LoyaltyPoints',
        'merchant_info': 'MerchantInfo',
        'price': 'Price',
        'type': 'Type',
        'violates_map': 'ViolatesMAP'
    }

    def __init__(self, availability=None, condition=None, deal_details=None, is_buy_box_winner=None,  # noqa: E501
                 loyalty_points=None, merchant_info=None, price=None, type=None, violates_map=None):
        """OffersV2Listing - a model defined in Swagger"""  # noqa: E501

        self._availability = None
        self._condition = None
        self._deal_details = None
        self._is_buy_box_winner = None
        self._loyalty_points = None
        self._merchant_info = None
        self._price = None
        self._type = None
        self._violates_map = None
        self.discriminator = None

        if availability is not None:
            self.availability = availability
        if condition is not None:
            self.condition = condition
        if deal_details is not None:
            self.deal_details = deal_details
        if is_buy_box_winner is not None:
            self.is_buy_box_winner = is_buy_box_winner
        if loyalty_points is not None:
            self.loyalty_points = loyalty_points
        if merchant_info is not None:
            self.merchant_info = merchant_info
        if price is not None:
            self.price = price
        if type is not None:
            self.type = type
        if violates_map is not None:
            self.violates_map = violates_map

    @property
    def availability(self):
        """Gets the availability of this OffersV2Listing.


        :return: The availability of this OffersV2Listing.
        :rtype: OffersV2Availability
        """
        return self._availability

    @availability.setter
    def availability(self, availability):
        """Sets the availability of this OffersV2Listing.


        :param availability: The availability of this OffersV2Listing.
        :type: OffersV2Availability
        """

        self._availability = availability

    @property
    def condition(self):
        """Gets the condition of this OffersV2Listing.


        :return: The condition of this OffersV2Listing.
        :rtype: OffersV2Condition
        """
        return self._condition

    @condition.setter
    def condition(self, condition):
        """Sets the condition of this OffersV2Listing.


        :param condition: The condition of this OffersV2Listing.
        :type: OffersV2Condition
        """

        self._condition = condition

    @property
    def deal_details(self):
        """Gets the deal_details of this OffersV2Listing.

        Deal information if available

        :return: The deal_details of this OffersV2Listing.
        :rtype: OffersV2DealDetails
        """
        return self._deal_details

    @deal_details.setter
    def deal_details(self, deal_details):
        """Sets the deal_details of this OffersV2Listing.

        :param deal_details: The deal_details of this OffersV2Listing.
        :type: OffersV2DealDetails
        """

        self._deal_details = deal_details

    @property
    def is_buy_box_winner(self):
        """Gets the is_buy_box_winner of this OffersV2Listing.

        Whether this offer is the BuyBox winner

        :return: The is_buy_box_winner of this OffersV2Listing.
        :rtype: bool
        """
        return self._is_buy_box_winner

    @is_buy_box_winner.setter
    def is_buy_box_winner(self, is_buy_box_winner):
        """Sets the is_buy_box_winner of this OffersV2Listing.

        :param is_buy_box_winner: The is_buy_box_winner of this OffersV2Listing.
        :type: bool
        """

        self._is_buy_box_winner = is_buy_box_winner

    @property
    def loyalty_points(self):
        """Gets the loyalty_points of this OffersV2Listing.

        Loyalty points (Japan only)

        :return: The loyalty_points of this OffersV2Listing.
        :rtype: OffersV2LoyaltyPoints
        """
        return self._loyalty_points

    @loyalty_points.setter
    def loyalty_points(self, loyalty_points):
        """Sets the loyalty_points of this OffersV2Listing.

        :param loyalty_points: The loyalty_points of this OffersV2Listing.
        :type: OffersV2LoyaltyPoints
        """

        self._loyalty_points = loyalty_points

    @property
    def merchant_info(self):
        """Gets the merchant_info of this OffersV2Listing.

        Merchant information

        :return: The merchant_info of this OffersV2Listing.
        :rtype: OffersV2MerchantInfo
        """
        return self._merchant_info

    @merchant_info.setter
    def merchant_info(self, merchant_info):
        """Sets the merchant_info of this OffersV2Listing.

        :param merchant_info: The merchant_info of this OffersV2Listing.
        :type: OffersV2MerchantInfo
        """

        self._merchant_info = merchant_info

    @property
    def price(self):
        """Gets the price of this OffersV2Listing.

        Price information

        :return: The price of this OffersV2Listing.
        :rtype: OffersV2Price
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this OffersV2Listing.

        :param price: The price of this OffersV2Listing.
        :type: OffersV2Price
        """

        self._price = price

    @property
    def type(self):
        """Gets the type of this OffersV2Listing.

        Offer type (LIGHTNING_DEAL, SUBSCRIBE_AND_SAVE, or None for regular offers)

        :return: The type of this OffersV2Listing.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this OffersV2Listing.

        :param type: The type of this OffersV2Listing.
        :type: str
        """

        self._type = type

    @property
    def violates_map(self):
        """Gets the violates_map of this OffersV2Listing.

        Whether the offer violates MAP policy

        :return: The violates_map of this OffersV2Listing.
        :rtype: bool
        """
        return self._violates_map

    @violates_map.setter
    def violates_map(self, violates_map):
        """Sets the violates_map of this OffersV2Listing.

        :param violates_map: The violates_map of this OffersV2Listing.
        :type: bool
        """

        self._violates_map = violates_map

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, attr_type in six.iteritems(self.swagger_types):
            value = getattr(self, attr, None)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true when self and other are equal"""
        if not isinstance(other, OffersV2Listing):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true when self and other are not equal"""
        return not self == other
