# coding: utf-8

"""
 Copyright 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License").
 You may not use this file except in compliance with the License.
 A copy of the License is located at

     http://www.apache.org/licenses/LICENSE-2.0

 or in the "license" file accompanying this file. This file is distributed
 on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 express or implied. See the License for the specific language governing
 permissions and limitations under the License.
"""

"""
    ProductAdvertisingAPI OffersV2 - SavingBasis

    https://webservices.amazon.com/paapi5/documentation/offersV2.html
"""

import pprint
import re
import six

from paapi5_python_sdk.offers_v2_money import OffersV2Money  # noqa: F401,E501


class OffersV2SavingBasis(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    
    Reference value used to calculate savings against
    """

    swagger_types = {
        'money': 'OffersV2Money',
        'saving_basis_type': 'str',
        'saving_basis_type_label': 'str'
    }

    attribute_map = {
        'money': 'Money',
        'saving_basis_type': 'SavingBasisType',
        'saving_basis_type_label': 'SavingBasisTypeLabel'
    }

    def __init__(self, money=None, saving_basis_type=None, saving_basis_type_label=None):  # noqa: E501
        """OffersV2SavingBasis - a model defined in Swagger"""  # noqa: E501

        self._money = None
        self._saving_basis_type = None
        self._saving_basis_type_label = None
        self.discriminator = None

        if money is not None:
            self.money = money
        if saving_basis_type is not None:
            self.saving_basis_type = saving_basis_type
        if saving_basis_type_label is not None:
            self.saving_basis_type_label = saving_basis_type_label

    @property
    def money(self):
        """Gets the money of this OffersV2SavingBasis.


        :return: The money of this OffersV2SavingBasis.
        :rtype: OffersV2Money
        """
        return self._money

    @money.setter
    def money(self, money):
        """Sets the money of this OffersV2SavingBasis.


        :param money: The money of this OffersV2SavingBasis.
        :type: OffersV2Money
        """

        self._money = money

    @property
    def saving_basis_type(self):
        """Gets the saving_basis_type of this OffersV2SavingBasis.

        Type of saving basis (LIST_PRICE, LOWEST_PRICE, LOWEST_PRICE_STRIKETHROUGH, WAS_PRICE)

        :return: The saving_basis_type of this OffersV2SavingBasis.
        :rtype: str
        """
        return self._saving_basis_type

    @saving_basis_type.setter
    def saving_basis_type(self, saving_basis_type):
        """Sets the saving_basis_type of this OffersV2SavingBasis.

        :param saving_basis_type: The saving_basis_type of this OffersV2SavingBasis.
        :type: str
        """

        self._saving_basis_type = saving_basis_type

    @property
    def saving_basis_type_label(self):
        """Gets the saving_basis_type_label of this OffersV2SavingBasis.

        Label for the saving basis type (e.g., "List Price")

        :return: The saving_basis_type_label of this OffersV2SavingBasis.
        :rtype: str
        """
        return self._saving_basis_type_label

    @saving_basis_type_label.setter
    def saving_basis_type_label(self, saving_basis_type_label):
        """Sets the saving_basis_type_label of this OffersV2SavingBasis.

        :param saving_basis_type_label: The saving_basis_type_label of this OffersV2SavingBasis.
        :type: str
        """

        self._saving_basis_type_label = saving_basis_type_label

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, attr_type in six.iteritems(self.swagger_types):
            value = getattr(self, attr, None)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true when self and other are equal"""
        if not isinstance(other, OffersV2SavingBasis):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true when self and other are not equal"""
        return not self == other
