# coding: utf-8

"""
 Copyright 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License").
 You may not use this file except in compliance with the License.
 A copy of the License is located at

     http://www.apache.org/licenses/LICENSE-2.0

 or in the "license" file accompanying this file. This file is distributed
 on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 express or implied. See the License for the specific language governing
 permissions and limitations under the License.
"""

"""
    ProductAdvertisingAPI OffersV2 - LoyaltyPoints

    https://webservices.amazon.com/paapi5/documentation/offersV2.html
"""

import pprint
import re
import six


class OffersV2LoyaltyPoints(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    
    Loyalty Points - Amazon Japan only program
    See: https://www.amazon.co.jp/-/en/gp/help/customer/display.html?nodeId=GGB6FCM85P9UKC7T
    """

    swagger_types = {
        'points': 'int'
    }

    attribute_map = {
        'points': 'Points'
    }

    def __init__(self, points=None):  # noqa: E501
        """OffersV2LoyaltyPoints - a model defined in Swagger"""  # noqa: E501

        self._points = None
        self.discriminator = None

        if points is not None:
            self.points = points

    @property
    def points(self):
        """Gets the points of this OffersV2LoyaltyPoints.

        Loyalty points associated with an offer

        :return: The points of this OffersV2LoyaltyPoints.
        :rtype: int
        """
        return self._points

    @points.setter
    def points(self, points):
        """Sets the points of this OffersV2LoyaltyPoints.

        :param points: The points of this OffersV2LoyaltyPoints.
        :type: int
        """

        self._points = points

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, attr_type in six.iteritems(self.swagger_types):
            value = getattr(self, attr, None)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true when self and other are equal"""
        if not isinstance(other, OffersV2LoyaltyPoints):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true when self and other are not equal"""
        return not self == other
