# coding: utf-8

"""
 Copyright 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License").
 You may not use this file except in compliance with the License.
 A copy of the License is located at

     http://www.apache.org/licenses/LICENSE-2.0

 or in the "license" file accompanying this file. This file is distributed
 on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 express or implied. See the License for the specific language governing
 permissions and limitations under the License.
"""

"""
    ProductAdvertisingAPI OffersV2 - Availability

    https://webservices.amazon.com/paapi5/documentation/offersV2.html
"""

import pprint
import re
import six


class OffersV2Availability(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    
    Availability types:
    - AVAILABLE_DATE: Item will be available on a future date
    - IN_STOCK: Item is in stock
    - IN_STOCK_SCARCE: Item is in stock but stock levels are limited
    - LEADTIME: Item available after lead time
    - OUT_OF_STOCK: Item is currently out of stock
    - PREORDER: Item can be pre-ordered
    - UNAVAILABLE: Item is not available
    - UNKNOWN: Unknown availability
    """

    swagger_types = {
        'type': 'str',
        'message': 'str',
        'min_order_quantity': 'int',
        'max_order_quantity': 'int'
    }

    attribute_map = {
        'type': 'Type',
        'message': 'Message',
        'min_order_quantity': 'MinOrderQuantity',
        'max_order_quantity': 'MaxOrderQuantity'
    }

    def __init__(self, type=None, message=None, min_order_quantity=None, max_order_quantity=None):  # noqa: E501
        """OffersV2Availability - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._message = None
        self._min_order_quantity = None
        self._max_order_quantity = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if message is not None:
            self.message = message
        if min_order_quantity is not None:
            self.min_order_quantity = min_order_quantity
        if max_order_quantity is not None:
            self.max_order_quantity = max_order_quantity

    @property
    def type(self):
        """Gets the type of this OffersV2Availability.

        Availability type (IN_STOCK, OUT_OF_STOCK, PREORDER, etc.)

        :return: The type of this OffersV2Availability.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this OffersV2Availability.

        :param type: The type of this OffersV2Availability.
        :type: str
        """
        self._type = type

    @property
    def message(self):
        """Gets the message of this OffersV2Availability.

        Availability message (e.g., "In Stock")

        :return: The message of this OffersV2Availability.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this OffersV2Availability.

        :param message: The message of this OffersV2Availability.
        :type: str
        """
        self._message = message

    @property
    def min_order_quantity(self):
        """Gets the min_order_quantity of this OffersV2Availability.

        Minimum quantity needed to make a purchase

        :return: The min_order_quantity of this OffersV2Availability.
        :rtype: int
        """
        return self._min_order_quantity

    @min_order_quantity.setter
    def min_order_quantity(self, min_order_quantity):
        """Sets the min_order_quantity of this OffersV2Availability.

        :param min_order_quantity: The min_order_quantity of this OffersV2Availability.
        :type: int
        """
        self._min_order_quantity = min_order_quantity

    @property
    def max_order_quantity(self):
        """Gets the max_order_quantity of this OffersV2Availability.

        Maximum quantity that can be purchased

        :return: The max_order_quantity of this OffersV2Availability.
        :rtype: int
        """
        return self._max_order_quantity

    @max_order_quantity.setter
    def max_order_quantity(self, max_order_quantity):
        """Sets the max_order_quantity of this OffersV2Availability.

        :param max_order_quantity: The max_order_quantity of this OffersV2Availability.
        :type: int
        """
        self._max_order_quantity = max_order_quantity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, attr_type in six.iteritems(self.swagger_types):
            value = getattr(self, attr, None)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true when self and other are equal"""
        if not isinstance(other, OffersV2Availability):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true when self and other are not equal"""
        return not self == other
