# coding: utf-8

"""
 Copyright 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License").
 You may not use this file except in compliance with the License.
 A copy of the License is located at

     http://www.apache.org/licenses/LICENSE-2.0

 or in the "license" file accompanying this file. This file is distributed
 on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 express or implied. See the License for the specific language governing
 permissions and limitations under the License.
"""

"""
    ProductAdvertisingAPI OffersV2 - Price

    https://webservices.amazon.com/paapi5/documentation/offersV2.html
"""

import pprint
import re
import six

from paapi5_python_sdk.offers_v2_money import OffersV2Money  # noqa: F401,E501
from paapi5_python_sdk.offers_v2_saving_basis import OffersV2SavingBasis  # noqa: F401,E501
from paapi5_python_sdk.offers_v2_savings import OffersV2Savings  # noqa: F401,E501


class OffersV2Price(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    
    Buying price and savings information for an offer.
    Note: Price shown represents the price for a logged-in Amazon user with in-marketplace shipping address.
    """

    swagger_types = {
        'money': 'OffersV2Money',
        'price_per_unit': 'OffersV2Money',
        'saving_basis': 'OffersV2SavingBasis',
        'savings': 'OffersV2Savings'
    }

    attribute_map = {
        'money': 'Money',
        'price_per_unit': 'PricePerUnit',
        'saving_basis': 'SavingBasis',
        'savings': 'Savings'
    }

    def __init__(self, money=None, price_per_unit=None, saving_basis=None, savings=None):  # noqa: E501
        """OffersV2Price - a model defined in Swagger"""  # noqa: E501

        self._money = None
        self._price_per_unit = None
        self._saving_basis = None
        self._savings = None
        self.discriminator = None

        if money is not None:
            self.money = money
        if price_per_unit is not None:
            self.price_per_unit = price_per_unit
        if saving_basis is not None:
            self.saving_basis = saving_basis
        if savings is not None:
            self.savings = savings

    @property
    def money(self):
        """Gets the money of this OffersV2Price.

        Buying amount

        :return: The money of this OffersV2Price.
        :rtype: OffersV2Money
        """
        return self._money

    @money.setter
    def money(self, money):
        """Sets the money of this OffersV2Price.

        :param money: The money of this OffersV2Price.
        :type: OffersV2Money
        """

        self._money = money

    @property
    def price_per_unit(self):
        """Gets the price_per_unit of this OffersV2Price.

        Price per unit (DisplayAmount includes unit formatting)

        :return: The price_per_unit of this OffersV2Price.
        :rtype: OffersV2Money
        """
        return self._price_per_unit

    @price_per_unit.setter
    def price_per_unit(self, price_per_unit):
        """Sets the price_per_unit of this OffersV2Price.

        :param price_per_unit: The price_per_unit of this OffersV2Price.
        :type: OffersV2Money
        """

        self._price_per_unit = price_per_unit

    @property
    def saving_basis(self):
        """Gets the saving_basis of this OffersV2Price.

        Reference value against which savings are calculated

        :return: The saving_basis of this OffersV2Price.
        :rtype: OffersV2SavingBasis
        """
        return self._saving_basis

    @saving_basis.setter
    def saving_basis(self, saving_basis):
        """Sets the saving_basis of this OffersV2Price.

        :param saving_basis: The saving_basis of this OffersV2Price.
        :type: OffersV2SavingBasis
        """

        self._saving_basis = saving_basis

    @property
    def savings(self):
        """Gets the savings of this OffersV2Price.

        Savings amount and percentage

        :return: The savings of this OffersV2Price.
        :rtype: OffersV2Savings
        """
        return self._savings

    @savings.setter
    def savings(self, savings):
        """Sets the savings of this OffersV2Price.

        :param savings: The savings of this OffersV2Price.
        :type: OffersV2Savings
        """

        self._savings = savings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, attr_type in six.iteritems(self.swagger_types):
            value = getattr(self, attr, None)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true when self and other are equal"""
        if not isinstance(other, OffersV2Price):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true when self and other are not equal"""
        return not self == other
